

export const SELECT_CURRENCY = "SELECT_CURRENCY";

export const ASYNC_LOAD_CURRENCIES = "ASYNC_LOAD_CURRENCIES";

export const LOAD_CURRENCIES = "LOAD_CURRENCIES";

export const ADD_WATCHER = "ADD_WATCHER";
export const ASYNC_ADD_WATCHER = "ASYNC_ADD_WATCHER";

export const GET_CURRENCY_PRICE = "GET_CURRENCY_PRICE";
export const ASYNC_GET_CURRENCY_PRICE = "ASYNC_GET_CURRENCY_PRICE";

export const REMOVE_WATCHER = "REMOVE_WATCHER";